name: Build CV
on:
  push:
    paths:
      - 'Alexander_Reinthal_CV.yaml'
      - '.github/workflows/makecv.yaml'
      - 'devenv.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Install devenv.sh
        run: |
          curl -L https://get.devenv.sh/latest-standalone | bash
          sudo mv devenv /usr/local/bin/

      - name: Build CV
        run: |
          devenv shell rendercv render Alexander_Reinthal_CV.yaml

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Commit and push generated CV files
        run: |
          git add Alexander_Reinthal_CV.pdf README.md
          git commit -m "Update CV files" || echo "No changes to commit"
          git push

